import 'models/quiz_item.dart';

const List<QuizItem> authors = [
  QuizItem(
    answer: 'William Shakespeare',
    imagePath: 'assets/images/authors/william_shakespeare.png',
    acceptedAnswers: [
      'Shakespeare',
      'William Shakespear',
    ],
    clues: [
      'I was born in the 16th century in Stratford-upon-Avon.',
      'My work includes comedies, tragedies and histories.',
      'I wrote for a theatre company called the Lord Chamberlain’s Men.',
      'One of my plays features three witches and a Scottish king.',
      'I wrote a tragedy about two young lovers from rival families.',
      'The Globe Theatre is closely associated with my work.',
      'I created characters including Hamlet, Othello and King Lear.',
      'I wrote Romeo and Juliet.',
      'I am often called the Bard of Avon.',
      'My first name is William.',
    ],
  ),
  QuizItem(
    answer: 'Jane Austen',
    imagePath: 'assets/images/authors/jane_austen.png',
    acceptedAnswers: [
      'Austen',
      'Jane Austin',
    ],
    clues: [
      'I published my novels anonymously during my lifetime.',
      'Most of my stories focus on family, marriage and social class.',
      'I wrote a novel featuring Anne Elliot.',
      'I created the Dashwood sisters.',
      'One of my novels centres on Emma Woodhouse.',
      'I wrote Sense and Sensibility.',
      'Mr Darcy is one of my most famous characters.',
      'I wrote Pride and Prejudice.',
      'I was an English novelist of the Regency era.',
      'My first name is Jane.',
    ],
  ),
  QuizItem(
    answer: 'Mark Twain',
    imagePath: 'assets/images/authors/mark_twain.png',
    acceptedAnswers: [
      'Twain',
      'Samuel Clemens',
      'Samuel Langhorne Clemens',
    ],
    clues: [
      'I worked as a riverboat pilot before becoming famous.',
      'My pen name comes from a river-depth measurement.',
      'I travelled widely and became known for my humour and lectures.',
      'I wrote a novel about a boy and an escaped enslaved man.',
      'The Mississippi River features heavily in my work.',
      'I created the character Huckleberry Finn.',
      'I also created Tom Sawyer.',
      'My real name was Samuel Clemens.',
      'I was an American writer and humourist.',
      'My surname as an author was Twain.',
    ],
  ),
  QuizItem(
    answer: 'Oscar Wilde',
    imagePath: 'assets/images/authors/oscar_wilde.png',
    acceptedAnswers: [
      'Wilde',
    ],
    clues: [
      'I was associated with the Aesthetic movement.',
      'I became famous for my wit, fashion and public lectures.',
      'I wrote a play featuring Lady Bracknell.',
      'One of my works centres on a portrait that ages instead of its subject.',
      'I wrote Salome.',
      'I wrote The Importance of Being Earnest.',
      'The Picture of Dorian Gray is my only novel.',
      'I was born in Dublin.',
      'I was an Irish playwright, poet and novelist.',
      'My first name is Oscar.',
    ],
  ),
  QuizItem(
    answer: 'Virginia Woolf',
    imagePath: 'assets/images/authors/virginia_woolf.png',
    acceptedAnswers: [
      'Woolf',
      'Virginia Wolf',
    ],
    clues: [
      'I was a central figure in the Bloomsbury Group.',
      'My writing often experiments with stream of consciousness.',
      'I helped run the Hogarth Press with my husband.',
      'I wrote a novel centred on the Ramsay family.',
      'I wrote Orlando.',
      'I wrote To the Lighthouse.',
      'One of my best-known essays is A Room of One’s Own.',
      'I wrote Mrs Dalloway.',
      'I was an English modernist writer.',
      'My first name is Virginia.',
    ],
  ),
];