// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeDgzehlgAsB4XsNmCmhEQdJKnfwCWfxk',
    appId: '1:752908982581:web:b5839fe9861b67f7ef547c',
    messagingSenderId: '752908982581',
    projectId: 'first-guess-a18b1',
    authDomain: 'first-guess-a18b1.firebaseapp.com',
    storageBucket: 'first-guess-a18b1.firebasestorage.app',
    measurementId: 'G-GC96G6WHPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQqWwxHYROijc_bRtIAEygkZ4m1JZGXNM',
    appId: '1:752908982581:android:3d78faaf8bfb812eef547c',
    messagingSenderId: '752908982581',
    projectId: 'first-guess-a18b1',
    storageBucket: 'first-guess-a18b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTqa8h_7RmQXLrlUfzqRprmPer5zcryaU',
    appId: '1:752908982581:ios:8935ad68ae6e131def547c',
    messagingSenderId: '752908982581',
    projectId: 'first-guess-a18b1',
    storageBucket: 'first-guess-a18b1.firebasestorage.app',
    iosBundleId: 'com.example.firstGuess',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeDgzehlgAsB4XsNmCmhEQdJKnfwCWfxk',
    appId: '1:752908982581:web:b155400c148a8000ef547c',
    messagingSenderId: '752908982581',
    projectId: 'first-guess-a18b1',
    authDomain: 'first-guess-a18b1.firebaseapp.com',
    storageBucket: 'first-guess-a18b1.firebasestorage.app',
    measurementId: 'G-XXLTYBRFGB',
  );
}
